{
    "CVE-ID": "CVE-2022-1508",
    "NVD": {
        "Descriptions": "An out-of-bounds read flaw was found in the Linux kernel\u2019s io_uring module in the way a user triggers the io_read() function with some special parameters. This flaw allows a local user to read some memory out of bounds.",
        "Cvss2_BaseScore": 0,
        "Cvss3_BaseScore": 6.1,
        "Cvss2_VectorString": "",
        "Cvss3_VectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:H",
        "CPEs": [
            {
                "URI": "cpe:/o:linux:linux_kernel",
                "FormattedString": "cpe:2.3:o:linux:linux_kernel:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "5.15",
                "VersionEndIncluding": ""
            }
        ]
    },
    "Official": {
        "5.15": {
            "source": [
                "https://www.kernel.org/pub//linux/kernel/v5.x/ChangeLog-5.15"
            ]
        },
        "commit": {
            "io_uring: reexpand under-reexpanded iters": [
                {
                    "description": "io_uring: reexpand under-reexpanded iters",
                    "commit": "89c2b3b74918200e46699338d7bcc19b1ea12110",
                    "source": "https://www.kernel.org/pub//linux/kernel/v5.x/ChangeLog-5.15",
                    "version": "5.15",
                    "upstream_commit": "",
                    "fixed": [
                        {
                            "fixed_commit": "1da177e4c3f4",
                            "fixed_commit_source": "https://www.kernel.org/pub//linux/kernel/v2.6/ChangeLog-2.6.12",
                            "fixed_commit_version": "2.6.12",
                            "fixed_commit_upstream_commit": []
                        }
                    ]
                }
            ]
        }
    }
}