{
    "CVE-ID": "CVE-2022-48733",
    "NVD": {
        "Descriptions": "In the Linux kernel, the following vulnerability has been resolved:\n\nbtrfs: fix use-after-free after failure to create a snapshot\n\nAt ioctl.c:create_snapshot(), we allocate a pending snapshot structure and\nthen attach it to the transaction's list of pending snapshots. After that\nwe call btrfs_commit_transaction(), and if that returns an error we jump\nto 'fail' label, where we kfree() the pending snapshot structure. This can\nresult in a later use-after-free of the pending snapshot:\n\n1) We allocated the pending snapshot and added it to the transaction's\n   list of pending snapshots;\n\n2) We call btrfs_commit_transaction(), and it fails either at the first\n   call to btrfs_run_delayed_refs() or btrfs_start_dirty_block_groups().\n   In both cases, we don't abort the transaction and we release our\n   transaction handle. We jump to the 'fail' label and free the pending\n   snapshot structure. We return with the pending snapshot still in the\n   transaction's list;\n\n3) Another task commits the transaction. This time there's no error at\n   all, and then during the transaction commit it accesses a pointer\n   to the pending snapshot structure that the snapshot creation task\n   has already freed, resulting in a user-after-free.\n\nThis issue could actually be detected by smatch, which produced the\nfollowing warning:\n\n  fs/btrfs/ioctl.c:843 create_snapshot() warn: '&pending_snapshot->list' not removed from list\n\nSo fix this by not having the snapshot creation ioctl directly add the\npending snapshot to the transaction's list. Instead add the pending\nsnapshot to the transaction handle, and then at btrfs_commit_transaction()\nwe add the snapshot to the list only when we can guarantee that any error\nreturned after that point will result in a transaction abort, in which\ncase the ioctl code can safely free the pending snapshot and no one can\naccess it anymore.",
        "Cvss2_BaseScore": 0,
        "Cvss3_BaseScore": 7.8,
        "Cvss2_VectorString": "",
        "Cvss3_VectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
        "CPEs": [
            {
                "URI": "cpe:/o:linux:linux_kernel",
                "FormattedString": "cpe:2.3:o:linux:linux_kernel:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "5.15.22",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/o:linux:linux_kernel",
                "FormattedString": "cpe:2.3:o:linux:linux_kernel:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "5.16",
                "VersionEndExcluding": "5.16.8",
                "VersionEndIncluding": ""
            }
        ]
    },
    "Official": {
        "5.10.226": {
            "source": [
                "https://www.kernel.org/pub//linux/kernel/v5.x/ChangeLog-5.10.226"
            ]
        },
        "5.15.22": {
            "source": [
                "https://www.kernel.org/pub//linux/kernel/v5.x/ChangeLog-5.15.22"
            ]
        },
        "5.16.8": {
            "source": [
                "https://www.kernel.org/pub//linux/kernel/v5.x/ChangeLog-5.16.8"
            ]
        },
        "5.17": {
            "source": [
                "https://www.kernel.org/pub//linux/kernel/v5.x/ChangeLog-5.17"
            ]
        },
        "commit": {
            "btrfs: fix use-after-free after failure to create a snapshot": [
                {
                    "description": "btrfs: fix use-after-free after failure to create a snapshot",
                    "commit": "7e4c72dbaf62f8978af8321a24dbd35566d3a78a",
                    "source": "https://www.kernel.org/pub//linux/kernel/v5.x/ChangeLog-5.10.226",
                    "version": "5.10.226",
                    "upstream_commit": "28b21c558a3753171097193b6f6602a94169093a",
                    "fixed": []
                },
                {
                    "description": "btrfs: fix use-after-free after failure to create a snapshot",
                    "commit": "a7b717fa15165d3d9245614680bebc48a52ac05d",
                    "source": "https://www.kernel.org/pub//linux/kernel/v5.x/ChangeLog-5.15.22",
                    "version": "5.15.22",
                    "upstream_commit": "28b21c558a3753171097193b6f6602a94169093a",
                    "fixed": []
                },
                {
                    "description": "btrfs: fix use-after-free after failure to create a snapshot",
                    "commit": "9372fa1d73da5f1673921e365d0cd2c27ec7adc2",
                    "source": "https://www.kernel.org/pub//linux/kernel/v5.x/ChangeLog-5.16.8",
                    "version": "5.16.8",
                    "upstream_commit": "28b21c558a3753171097193b6f6602a94169093a",
                    "fixed": []
                },
                {
                    "description": "btrfs: fix use-after-free after failure to create a snapshot",
                    "commit": "28b21c558a3753171097193b6f6602a94169093a",
                    "source": "https://www.kernel.org/pub//linux/kernel/v5.x/ChangeLog-5.17",
                    "version": "5.17",
                    "upstream_commit": "",
                    "fixed": [
                        {
                            "fixed_commit": "3063d29f2a4d",
                            "fixed_commit_source": "https://github.com/torvalds/linux/commit/3063d29f2a4d",
                            "fixed_commit_version": "-",
                            "fixed_commit_upstream_commit": []
                        }
                    ]
                }
            ]
        }
    }
}