{
    "CVE-ID": "CVE-2014-4650",
    "NVD": {
        "Descriptions": "The CGIHTTPServer module in Python 2.7.5 and 3.3.4 does not properly handle URLs in which URL encoding is used for path separators, which allows remote attackers to read script source code or conduct directory traversal attacks and execute unintended code via a crafted character sequence, as demonstrated by a %2f separator.",
        "Cvss2_BaseScore": 7.5,
        "Cvss3_BaseScore": 9.8,
        "Cvss2_VectorString": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
        "Cvss3_VectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "CPEs": [
            {
                "URI": "cpe:/o:redhat:enterprise_linux:7.0",
                "FormattedString": "cpe:2.3:o:redhat:enterprise_linux:7.0:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/o:redhat:enterprise_linux:6.0",
                "FormattedString": "cpe:2.3:o:redhat:enterprise_linux:6.0:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/o:redhat:enterprise_linux:5.0",
                "FormattedString": "cpe:2.3:o:redhat:enterprise_linux:5.0:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:redhat:software_collections:-",
                "FormattedString": "cpe:2.3:a:redhat:software_collections:-:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "2.7.0",
                "VersionEndExcluding": "2.7.8",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.2.0",
                "VersionEndExcluding": "3.2.6",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.3.0",
                "VersionEndExcluding": "3.3.6",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.4.0",
                "VersionEndExcluding": "3.4.2",
                "VersionEndIncluding": ""
            }
        ]
    },
    "Official": {
        "2.7.8": {
            "source": [
                "https://github.com/python/cpython/blob/2.7/Misc/NEWS.d/2.7.8.rst"
            ],
            "BTS": {
                "bpo21766": {
                    "ID": "bpo21766",
                    "url": "https://bugs.python.org/issue21766",
                    "date": "9359",
                    "nonce": "0xk_xC",
                    "section": "Library"
                }
            }
        },
        "3.3.6": {
            "source": [
                "https://github.com/python/cpython/blob/3.3/Misc/NEWS.d/3.3.6.rst"
            ],
            "BTS": {
                "bpo21766": {
                    "ID": "bpo21766",
                    "url": "https://bugs.python.org/issue21766",
                    "date": "9956",
                    "nonce": "0xk_xC",
                    "section": "Library"
                }
            }
        },
        "3.4.2rc1": {
            "source": [
                "https://github.com/python/cpython/blob/3.4/Misc/NEWS.d/3.4.2rc1.rst"
            ],
            "BTS": {
                "bpo21766": {
                    "ID": "bpo21766",
                    "url": "https://bugs.python.org/issue21766",
                    "date": "9509",
                    "nonce": "0xk_xC",
                    "section": "Library"
                }
            }
        },
        "3.5.0a1": {
            "source": [
                "https://github.com/python/cpython/blob/main/Misc/NEWS.d/3.5.0a1.rst"
            ],
            "BTS": {
                "bpo21766": {
                    "ID": "bpo21766",
                    "url": "https://bugs.python.org/issue21766",
                    "date": "8612",
                    "nonce": "0xk_xC",
                    "section": "Library"
                }
            }
        },
        "3.2.6": {
            "source": [
                "https://github.com/python/cpython/blob/3.2/Misc/NEWS"
            ],
            "BTS": {
                "bpo21766": {
                    "ID": "bpo21766",
                    "url": "https://bugs.python.org/issue21766",
                    "date": "",
                    "nonce": "",
                    "section": ""
                }
            }
        },
        "3.4.2": {
            "source": [
                "https://github.com/python/cpython/blob/v3.4.2rc1/Misc/NEWS"
            ],
            "BTS": {
                "bpo21766": {
                    "ID": "bpo21766",
                    "url": "https://bugs.python.org/issue21766",
                    "date": "",
                    "nonce": "",
                    "section": ""
                }
            }
        },
        "3.5a1": {
            "source": [
                "https://github.com/python/cpython/blob/v3.5.0a1/Misc/NEWS"
            ],
            "BTS": {
                "bpo21766": {
                    "ID": "bpo21766",
                    "url": "https://bugs.python.org/issue21766",
                    "date": "",
                    "nonce": "",
                    "section": ""
                }
            }
        }
    }
}