{
    "CVE-ID": "CVE-2016-1000110",
    "NVD": {
        "Descriptions": "The CGIHandler class in Python before 2.7.12 does not protect against the HTTP_PROXY variable name clash in a CGI script, which could allow a remote attacker to redirect HTTP requests.",
        "Cvss2_BaseScore": 5.8,
        "Cvss3_BaseScore": 6.1,
        "Cvss2_VectorString": "AV:N/AC:M/Au:N/C:P/I:P/A:N",
        "Cvss3_VectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
        "CPEs": [
            {
                "URI": "cpe:/o:fedoraproject:fedora:23",
                "FormattedString": "cpe:2.3:o:fedoraproject:fedora:23:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/o:debian:debian_linux:9.0",
                "FormattedString": "cpe:2.3:o:debian:debian_linux:9.0:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/o:debian:debian_linux:8.0",
                "FormattedString": "cpe:2.3:o:debian:debian_linux:8.0:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/o:debian:debian_linux:10.0",
                "FormattedString": "cpe:2.3:o:debian:debian_linux:10.0:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "2.7.12",
                "VersionEndIncluding": ""
            }
        ]
    },
    "Official": {
        "2.7.13rc1": {
            "source": [
                "https://github.com/python/cpython/blob/2.7/Misc/NEWS.d/2.7.13rc1.rst",
                "https://github.com/python/cpython/blob/v2.7.13rc1/Misc/NEWS"
            ],
            "BTS": {
                "bpo27568": {
                    "ID": "bpo27568",
                    "url": "https://bugs.python.org/issue27568",
                    "date": "9865",
                    "nonce": "OnuO9s",
                    "section": "Library"
                }
            }
        },
        "3.3.7rc1": {
            "source": [
                "https://github.com/python/cpython/blob/3.3/Misc/NEWS.d/3.3.7rc1.rst"
            ],
            "BTS": {
                "bpo27568": {
                    "ID": "bpo27568",
                    "url": "https://bugs.python.org/issue27568",
                    "date": "014",
                    "nonce": "OnuO9s",
                    "section": "Library"
                }
            }
        },
        "3.4.6rc1": {
            "source": [
                "https://github.com/python/cpython/blob/3.4/Misc/NEWS.d/3.4.6rc1.rst",
                "https://github.com/python/cpython/blob/3.6/Misc/HISTORY"
            ],
            "BTS": {
                "bpo27568": {
                    "ID": "bpo27568",
                    "url": "https://bugs.python.org/issue27568",
                    "date": "9986",
                    "nonce": "OnuO9s",
                    "section": "Library"
                }
            }
        },
        "3.5.3rc1": {
            "source": [
                "https://github.com/python/cpython/blob/v3.8.0b1/Misc/NEWS.d/3.5.3rc1.rst",
                "https://github.com/python/cpython/blob/v3.5.3rc1/Misc/NEWS"
            ],
            "BTS": {
                "bpo27568": {
                    "ID": "bpo27568",
                    "url": "https://bugs.python.org/issue27568",
                    "date": "9773",
                    "nonce": "OnuO9s",
                    "section": "Library"
                }
            }
        },
        "3.6.0a4": {
            "source": [
                "https://github.com/python/cpython/blob/v3.8.0a1/Misc/NEWS.d/3.6.0a4.rst",
                "https://github.com/python/cpython/blob/v3.6.0a4/Misc/NEWS"
            ],
            "BTS": {
                "bpo27568": {
                    "ID": "bpo27568",
                    "url": "https://bugs.python.org/issue27568",
                    "date": "9419",
                    "nonce": "OnuO9s",
                    "section": "Library"
                }
            }
        }
    }
}