{
    "CVE-ID": "CVE-2020-8315",
    "NVD": {
        "Descriptions": "In Python (CPython) 3.6 through 3.6.10, 3.7 through 3.7.6, and 3.8 through 3.8.1, an insecure dependency load upon launch on Windows 7 may result in an attacker's copy of api-ms-win-core-path-l1-1-0.dll being loaded and used instead of the system's copy. Windows 8 and later are unaffected.",
        "Cvss2_BaseScore": 4.3,
        "Cvss3_BaseScore": 5.5,
        "Cvss2_VectorString": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
        "Cvss3_VectorString": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N",
        "CPEs": [
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.6.0",
                "VersionEndExcluding": "",
                "VersionEndIncluding": "3.6.10"
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.7.0",
                "VersionEndExcluding": "",
                "VersionEndIncluding": "3.7.6"
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.8.0",
                "VersionEndExcluding": "",
                "VersionEndIncluding": "3.8.1"
            }
        ]
    },
    "Official": {
        "3.6.11rc1": {
            "source": [
                "https://github.com/python/cpython/blob/3.6/Misc/NEWS.d/3.6.11rc1.rst"
            ],
            "BTS": {
                "bpo39401": {
                    "ID": "bpo39401",
                    "url": "https://bugs.python.org/issue39401",
                    "date": "2020-01-28-20-54-09",
                    "nonce": "he7h_A",
                    "section": "Security"
                }
            }
        },
        "3.7.7rc1": {
            "source": [
                "https://github.com/python/cpython/blob/v3.7.7rc1/Misc/NEWS.d/3.7.7rc1.rst"
            ],
            "BTS": {
                "bpo39401": {
                    "ID": "bpo39401",
                    "url": "https://bugs.python.org/issue39401",
                    "date": "2020-01-28-20-54-09",
                    "nonce": "he7h_A",
                    "section": "Security"
                }
            }
        },
        "3.8.2rc1": {
            "source": [
                "https://github.com/python/cpython/blob/v3.8.2rc1/Misc/NEWS.d/3.8.2rc1.rst"
            ],
            "BTS": {
                "bpo39401": {
                    "ID": "bpo39401",
                    "url": "https://bugs.python.org/issue39401",
                    "date": "2020-01-28-20-54-09",
                    "nonce": "he7h_A",
                    "section": "Security"
                }
            }
        },
        "3.9.0a4": {
            "source": [
                "https://github.com/python/cpython/blob/v3.11.4/Misc/NEWS.d/3.9.0a4.rst"
            ],
            "BTS": {
                "bpo39401": {
                    "ID": "bpo39401",
                    "url": "https://bugs.python.org/issue39401",
                    "date": "2020-01-28-20-54-09",
                    "nonce": "he7h_A",
                    "section": "Security"
                }
            }
        }
    }
}