{
    "CVE-ID": "CVE-2019-9674",
    "NVD": {
        "Descriptions": "Lib/zipfile.py in Python through 3.7.2 allows remote attackers to cause a denial of service (resource consumption) via a ZIP bomb.",
        "Cvss2_BaseScore": 5,
        "Cvss3_BaseScore": 7.5,
        "Cvss2_VectorString": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
        "Cvss3_VectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
        "CPEs": [
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": "3.7.2"
            }
        ]
    },
    "Official": {
        "3.8.0rc1": {
            "source": [
                "https://github.com/python/cpython/blob/v3.8.0rc1/Misc/NEWS.d/3.8.0rc1.rst"
            ],
            "BTS": {
                "bpo36260": {
                    "ID": "bpo36260",
                    "url": "https://bugs.python.org/issue36260",
                    "date": "2019-06-04-09-29-00",
                    "nonce": "WrGuc-",
                    "section": "Documentation"
                }
            }
        },
        "3.9.0a1": {
            "source": [
                "https://github.com/python/cpython/blob/v3.10.0/Misc/NEWS.d/3.9.0a1.rst"
            ],
            "BTS": {
                "bpo36260": {
                    "ID": "bpo36260",
                    "url": "https://bugs.python.org/issue36260",
                    "date": "2019-06-04-09-29-00",
                    "nonce": "WrGuc-",
                    "section": "Documentation"
                }
            }
        }
    }
}