{
    "CVE-ID": "CVE-2014-4616",
    "NVD": {
        "Descriptions": "Array index error in the scanstring function in the _json module in Python 2.7 through 3.5 and simplejson before 2.6.1 allows context-dependent attackers to read arbitrary process memory via a negative index value in the idx argument to the raw_decode function.",
        "Cvss2_BaseScore": 4.3,
        "Cvss3_BaseScore": 5.9,
        "Cvss2_VectorString": "AV:N/AC:M/Au:N/C:P/I:N/A:N",
        "Cvss3_VectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N",
        "CPEs": [
            {
                "URI": "cpe:/o:opensuse_project:opensuse:12.3",
                "FormattedString": "cpe:2.3:o:opensuse_project:opensuse:12.3:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/o:opensuse:opensuse:13.1",
                "FormattedString": "cpe:2.3:o:opensuse:opensuse:13.1:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:simplejson_project:simplejson:::~~~python~~",
                "FormattedString": "cpe:2.3:a:simplejson_project:simplejson:*:*:*:*:*:python:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "2.6.1",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "2.7.0",
                "VersionEndExcluding": "2.7.7",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.0.0",
                "VersionEndExcluding": "3.2.6",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.3.0",
                "VersionEndExcluding": "3.3.6",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.4.0",
                "VersionEndExcluding": "3.4.1",
                "VersionEndIncluding": ""
            }
        ]
    },
    "Official": {
        "2.7.7rc1": {
            "source": [
                "https://github.com/python/cpython/blob/2.7/Misc/NEWS.d/2.7.7rc1.rst",
                "https://github.com/python/cpython/blob/v2.7.11/Misc/NEWS"
            ],
            "BTS": {
                "bpo21529": {
                    "ID": "bpo21529",
                    "url": "https://bugs.python.org/issue21529",
                    "date": "9307",
                    "nonce": "57R_Fc",
                    "section": "Library"
                }
            }
        },
        "3.3.6": {
            "source": [
                "https://github.com/python/cpython/blob/3.3/Misc/NEWS.d/3.3.6.rst"
            ],
            "BTS": {
                "bpo21529": {
                    "ID": "bpo21529",
                    "url": "https://bugs.python.org/issue21529",
                    "date": "9948",
                    "nonce": "57R_Fc",
                    "section": "Library"
                }
            }
        },
        "3.4.1rc1": {
            "source": [
                "https://github.com/python/cpython/blob/3.4/Misc/NEWS.d/3.4.1rc1.rst",
                "https://github.com/python/cpython/blob/3.6/Misc/HISTORY"
            ],
            "BTS": {
                "bpo21529": {
                    "ID": "bpo21529",
                    "url": "https://bugs.python.org/issue21529",
                    "date": "9407",
                    "nonce": "57R_Fc",
                    "section": "Library"
                }
            }
        },
        "3.5.0a1": {
            "source": [
                "https://github.com/python/cpython/blob/v3.11.8/Misc/NEWS.d/3.5.0a1.rst"
            ],
            "BTS": {
                "bpo21529": {
                    "ID": "bpo21529",
                    "url": "https://bugs.python.org/issue21529",
                    "date": "8539",
                    "nonce": "57R_Fc",
                    "section": "Library"
                }
            }
        },
        "3.2.6": {
            "source": [
                "https://github.com/python/cpython/blob/3.2/Misc/NEWS"
            ],
            "BTS": {
                "bpo21529": {
                    "ID": "bpo21529",
                    "url": "https://bugs.python.org/issue21529",
                    "date": "",
                    "nonce": "",
                    "section": ""
                }
            }
        },
        "3.5a1": {
            "source": [
                "https://github.com/python/cpython/blob/v3.5.2rc1/Misc/NEWS"
            ],
            "BTS": {
                "bpo21529": {
                    "ID": "bpo21529",
                    "url": "https://bugs.python.org/issue21529",
                    "date": "",
                    "nonce": "",
                    "section": ""
                }
            }
        }
    }
}