{
    "CVE-ID": "CVE-2017-9233",
    "NVD": {
        "Descriptions": "XML External Entity vulnerability in libexpat 2.2.0 and earlier (Expat XML Parser Library) allows attackers to put the parser in an infinite loop using a malformed external entity definition from an external DTD.",
        "Cvss2_BaseScore": 5,
        "Cvss3_BaseScore": 7.5,
        "Cvss2_VectorString": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
        "Cvss3_VectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
        "CPEs": [
            {
                "URI": "cpe:/a:libexpat_project:libexpat",
                "FormattedString": "cpe:2.3:a:libexpat_project:libexpat:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": "2.2.0"
            }
        ]
    },
    "Official": {
        "2.7.15rc1": {
            "source": [
                "https://github.com/python/cpython/blob/2.7/Misc/NEWS.d/2.7.15rc1.rst"
            ],
            "BTS": {
                "bpo30694": {
                    "ID": "bpo30694",
                    "url": "https://bugs.python.org/issue30694",
                    "date": "059",
                    "nonce": "WkMWM_",
                    "section": "Security"
                }
            }
        },
        "3.3.7rc1": {
            "source": [
                "https://github.com/python/cpython/blob/3.3/Misc/NEWS.d/3.3.7rc1.rst"
            ],
            "BTS": {
                "bpo30694": {
                    "ID": "bpo30694",
                    "url": "https://bugs.python.org/issue30694",
                    "date": "021",
                    "nonce": "WkMWM_",
                    "section": "Security"
                }
            }
        },
        "3.4.7rc1": {
            "source": [
                "https://github.com/python/cpython/blob/3.4/Misc/NEWS.d/3.4.7rc1.rst"
            ],
            "BTS": {
                "bpo30694": {
                    "ID": "bpo30694",
                    "url": "https://bugs.python.org/issue30694",
                    "date": "2017-07-11-22-25-24",
                    "nonce": "oOf3Er",
                    "section": "Security"
                }
            }
        },
        "3.5.4rc1": {
            "source": [
                "https://github.com/python/cpython/blob/3.5/Misc/NEWS.d/3.5.4rc1.rst"
            ],
            "BTS": {
                "bpo30694": {
                    "ID": "bpo30694",
                    "url": "https://bugs.python.org/issue30694",
                    "date": "083",
                    "nonce": "WkMWM_",
                    "section": "Security"
                }
            }
        },
        "3.6.2rc2": {
            "source": [
                "https://github.com/python/cpython/blob/3.6/Misc/NEWS.d/3.6.2rc2.rst",
                "https://github.com/python/cpython/blob/v3.6.2rc2/Misc/NEWS"
            ],
            "BTS": {
                "bpo30694": {
                    "ID": "bpo30694",
                    "url": "https://bugs.python.org/issue30694",
                    "date": "9991",
                    "nonce": "WkMWM_",
                    "section": "Security"
                }
            }
        },
        "3.7.0a1": {
            "source": [
                "https://github.com/python/cpython/blob/v3.7.0a1/Misc/NEWS.d/3.7.0a1.rst"
            ],
            "BTS": {
                "bpo30694": {
                    "ID": "bpo30694",
                    "url": "https://bugs.python.org/issue30694",
                    "date": "0344",
                    "nonce": "WkMWM_",
                    "section": "Security"
                }
            }
        },
        "2.7.14rc1": {
            "source": [
                "https://github.com/python/cpython/blob/v2.7.14rc1/Misc/NEWS"
            ]
        }
    }
}