{
    "CVE-ID": "CVE-2020-27619",
    "NVD": {
        "Descriptions": "In Python 3 through 3.9.0, the Lib/test/multibytecodec_support.py CJK codec tests call eval() on content retrieved via HTTP.",
        "Cvss2_BaseScore": 7.5,
        "Cvss3_BaseScore": 9.8,
        "Cvss2_VectorString": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
        "Cvss3_VectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "CPEs": [
            {
                "URI": "cpe:/o:fedoraproject:fedora:34",
                "FormattedString": "cpe:2.3:o:fedoraproject:fedora:34:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/o:fedoraproject:fedora:33",
                "FormattedString": "cpe:2.3:o:fedoraproject:fedora:33:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.0.0",
                "VersionEndExcluding": "3.6.13",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.7.0",
                "VersionEndExcluding": "3.7.10",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.8.0",
                "VersionEndExcluding": "3.8.7",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.9.0",
                "VersionEndExcluding": "3.9.1",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:oracle:communications_cloud_native_core_network_function_cloud_native_environment:22.2.0",
                "FormattedString": "cpe:2.3:a:oracle:communications_cloud_native_core_network_function_cloud_native_environment:22.2.0:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            }
        ]
    },
    "Official": {
        "3.6.13": {
            "source": [
                "https://github.com/python/cpython/blob/3.6/Misc/NEWS.d/3.6.13.rst"
            ],
            "BTS": {
                "bpo41944": {
                    "ID": "bpo41944",
                    "url": "https://bugs.python.org/issue41944",
                    "date": "2020-10-05-17-43-46",
                    "nonce": "rf1dYb",
                    "section": "Tests"
                }
            }
        },
        "3.7.10": {
            "source": [
                "https://github.com/python/cpython/blob/3.7/Misc/NEWS.d/3.7.10.rst"
            ],
            "BTS": {
                "bpo41944": {
                    "ID": "bpo41944",
                    "url": "https://bugs.python.org/issue41944",
                    "date": "2020-10-05-17-43-46",
                    "nonce": "rf1dYb",
                    "section": "Tests"
                }
            }
        },
        "3.8.7rc1": {
            "source": [
                "https://github.com/python/cpython/blob/v3.8.7/Misc/NEWS.d/3.8.7rc1.rst"
            ],
            "BTS": {
                "bpo41944": {
                    "ID": "bpo41944",
                    "url": "https://bugs.python.org/issue41944",
                    "date": "2020-10-05-17-43-46",
                    "nonce": "rf1dYb",
                    "section": "Tests"
                }
            }
        },
        "3.9.1rc1": {
            "source": [
                "https://github.com/python/cpython/blob/v3.9.8/Misc/NEWS.d/3.9.1rc1.rst"
            ],
            "BTS": {
                "bpo41944": {
                    "ID": "bpo41944",
                    "url": "https://bugs.python.org/issue41944",
                    "date": "2020-10-05-17-43-46",
                    "nonce": "rf1dYb",
                    "section": "Tests"
                }
            }
        },
        "3.10.0a2": {
            "source": [
                "https://github.com/python/cpython/blob/v3.12.0a7/Misc/NEWS.d/3.10.0a2.rst"
            ],
            "BTS": {
                "bpo41944": {
                    "ID": "bpo41944",
                    "url": "https://bugs.python.org/issue41944",
                    "date": "2020-10-05-17-43-46",
                    "nonce": "rf1dYb",
                    "section": "Tests"
                }
            }
        }
    }
}